
export const splashtext: readonly string[] = [
	`meow`,
	`meow meow meow meow, meow meow`,
	`meow mrrppp meow meow`,
	`meoww meowww meow meow`,
	`mew!`,
	`meow meow ? meow meow meow.`,
	`mrppp meow meow meow`,
	`meow! meow! meow! meow! meow!`,
	`purrrr`,
	`meow meow meow`,
	`???`,
	`meow meow meow`,
	`meowmeowmeowmeowmeowmeowmeow`,
	`meow? meow meow? meow meow?? meow??`,
	`meow...`,
	`meow! lkjfdklsdjf`,
	`the industrial revolution and its consequences`,
	`meow meow, meow? meow?`,
	`meow? meow.`,
	`meow! mrppp meow mew meow`,
	`meow mew nya mreow miau mrp pur`,
	`mew meow meow`,
	`nyyya!`,
	`nya nyemo nyumew mew`,
	`meow!!!!!!!!!!!!!`,
	`meow meow meow, meow meow meow`,
	`mmmmreow!`,
	`actually, I don't even think I'm a cat.`,
	`meow ! meow! meow !! meow :3 :3`,
	`:3`,
	`>:3`,
	`meow :3`,
	`meow ~~`,
	`meow >:3`,
	`meow meow meow meow meow meow (:3)`,
	`meow meow, meow meow meow. meow meow (Meow p.32)`,
	`meow! ?? meow meow :3 meow`,
	`:3c`,
	`meow meow meowwwww >:3`,
	`<:3`,
	`;3`,
	`>;3`,
	`>:3c`,
	`>;3c`,
	`X3`,
	`3:`,
	`m30\\/\\/`,
	`made with catfeine`,
	`ᓚᘏᗢ`,
	`ฅ^>⩊<^ฅ`,
	`≽^•⩊•^≼`,
	`≽(•⩊ •マ≼`,
	`𓃠`,
	`>⩊<`,
	`=ᗢ=`,
	`‧₊˚♪ 𝄞₊˚⊹`,
	`°❀⋆.ೃ࿔*:･`,
	`. ݁₊ ⊹ . ݁˖ . ݁`,
	`/ᐠ - ˕ -マ Ⳋ`,
	`ฅ(ᵔ꒳ ᵔマ.ᐟ`,
	`𐔌˙.`,
	`^._.^`,
	`Φ ω Φ`,
	`/ᐠ｡ꞈ｡ᐟ\\`,
	`/ᐠ .ᆺ. ᐟ\\ﾉ`,
	`^ↀᴥↀ^`,
	`~(=^･ω･^)ﾍ >ﾟ)))彡`,
	`ㅇㅅㅇ`,
	`(ㅇㅅㅇ❀)`,
];

